### ISSUE TITLE
[Suggestion] Replace scrolling nav on mobile with hamburger / similar

### ISSUE THREAD

**Issue by AllanOcelot** [AnandChowdhary/anandchowdhary.com#100]
Nothing wrong with the scrolling nav on mobile, but many users (Myself included) will not find it intuitive. A hamburger menu might seem boring, but it works.

![image](https://user-images.githubusercontent.com/11334905/66748187-7784e980-ee7e-11e9-8707-f6477e78b998.png)

**Comment by AnandChowdhary** [comment]
Fixed in the upcoming version!
