### ISSUE TITLE
[Suggestion] Close icon for  'Try light mode' 

### ISSUE THREAD

**Issue by AllanOcelot** [AnandChowdhary/anandchowdhary.com#101]
The 'Try light mode' is always at the top of the site, it would be nice to have a simple close icon, that sets a cookie/localstore remembering I do not wish to use light mode :)

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @AllanOcelot! I added that message as a temporary way to inform users since there's no toggle for dark/light theme, but it uses the system preference. I think it's time to get rid of it now. :)
